### ISSUE TITLE
Star this Repository!

### ISSUE THREAD

**Issue by WickedBrat** [agbilotia1998/Lecture-Connect#12]
Go ahead star this repo and share the SS here!

**Comment by Jigar3** [comment]
![screenshot_2018-01-12-10-47-14-603_com android chrome](https://user-images.githubusercontent.com/32068121/34860797-031b2988-f786-11e7-9e89-218a5ec9c9b0.png)

**Comment by maverick0004** [comment]
![screenshot 20](https://user-images.githubusercontent.com/33194760/34861490-5c7e7cf0-f78b-11e7-9f08-3fed02a96762.png)

**Comment by Re42** [comment]
![image](https://user-images.githubusercontent.com/33805964/34861980-caf76b0e-f78d-11e7-8939-f462315433a9.png)

**Comment by marshallKR7** [comment]
![screenshot-2018-1-12 star this repository issue 12 agbilotia1998 lecture-connect](https://user-images.githubusercontent.com/28799332/34862714-cdfc5342-f791-11e7-9b72-1a4dd74e9937.png)

**Comment by muskan6769** [comment]
![screenshot from 2018-01-12 13-17-46](https://user-images.githubusercontent.com/34505804/34864602-09cb46ae-f79b-11e7-95c2-162895257d41.png)

**Comment by Tlazypanda** [comment]
![image](https://user-images.githubusercontent.com/33183263/34866112-5e27acf0-f7a1-11e7-8922-0e8e8a6a7f98.png)

**Comment by vvvinamer** [comment]
![screenshot 30](https://user-images.githubusercontent.com/35339278/34868576-460700e0-f7aa-11e7-8e18-f196c6a2c43a.png)

**Comment by adiagg2000** [comment]
![screenshot 38](https://user-images.githubusercontent.com/33027339/34869607-700f31a2-f7ad-11e7-9c04-2600cf23500c.png)

**Comment by prathamprakash29** [comment]
![image](https://user-images.githubusercontent.com/30841366/34870073-ff55cf14-f7ae-11e7-8410-09523b5ffd5c.png)

**Comment by AlphaCholera** [comment]
![screenshot from 2018-01-12 21-10-48](https://user-images.githubusercontent.com/33174671/34870079-06f90b64-f7af-11e7-8e55-de63a5e5be0a.png)

**Comment by hacker1x1x1** [comment]
![image](https://user-images.githubusercontent.com/34509429/34872341-5fed89b2-f745-11e7-823a-7c54e830b652.png)

**Comment by GOVINDDIXIT** [comment]
![s](https://user-images.githubusercontent.com/32304546/34874146-d7697492-f7bd-11e7-99c3-acb8a5b3d6a3.PNG)

**Comment by strikertanmay** [comment]
![screenshot from 2018-01-12 17-47-55](https://user-images.githubusercontent.com/32292953/34874858-c7b07476-f7c0-11e7-9299-3a191e5db525.png)

**Comment by Divy123** [comment]
![screenshot from 2018-01-12 20-25-23](https://user-images.githubusercontent.com/31225007/34880545-cb87016c-f7d6-11e7-8bb2-de31e05bfa91.png)

**Comment by Panda2498** [comment]
![lecture-connect](https://user-images.githubusercontent.com/34282889/34888943-3b5854d0-f7f2-11e7-8ccc-2dede6efcb2c.PNG)

**Comment by Esha23** [comment]
![screenshot-2018-1-13 agbilotia1998 lecture-connect](https://user-images.githubusercontent.com/35305010/34896905-93f647f4-f811-11e7-8ca7-8ea92d0afdc3.png)

**Comment by WickedBrat** [comment]
Welcome to Lecture Connect Everyone. Have a look at issue #2 to get started.

**Comment by rahulkumaran** [comment]
![new](https://user-images.githubusercontent.com/26206171/35779890-4843b242-09fa-11e8-9794-21479f3ac2cb.png)
